// Script to parse third-place combinations from Wikipedia data
// Run with: node scripts/parseThirdPlaceCombinations.js

const fs = require('fs')
const path = require('path')

// The raw data extracted from Wikipedia
// Format: Each combination has:
// - ID number
// - 8 qualifying groups (from A-L)
// - 8 assignments (which 3rd place group each winner plays)
//
// Group winners that play 3rd place teams:
// 1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L (in that order in the table)

const rawData = `
1|EFGHIJKL|E|J|I|F|H|G|L|K
2|DFGHIJKL|H|G|I|D|J|F|L|K
3|DEGHIJKL|E|J|I|D|H|G|L|K
4|DEFHIJKL|E|J|I|D|H|F|L|K
5|DEFGIJKL|E|G|I|D|J|F|L|K
6|DEFGHJKL|E|G|J|D|H|F|L|K
7|DEFGHIKL|E|G|I|D|H|F|L|K
8|DEFGHIJL|E|G|J|D|H|F|L|I
9|DEFGHIJK|E|G|J|D|H|F|I|K
10|CFGHIJKL|H|G|I|C|J|F|L|K
11|CEGHIJKL|E|J|I|C|H|G|L|K
12|CEFHIJKL|E|J|I|C|H|F|L|K
13|CEFGIJKL|E|G|I|C|J|F|L|K
14|CEFGHJKL|E|G|J|C|H|F|L|K
15|CEFGHIKL|E|G|I|C|H|F|L|K
16|CEFGHIJL|E|G|J|C|H|F|L|I
17|CEFGHIJK|E|G|J|C|H|F|I|K
18|CDGHIJKL|H|G|I|C|J|D|L|K
19|CDFHIJKL|C|J|I|D|H|F|L|K
20|CDFGIJKL|C|G|I|D|J|F|L|K
21|CDFGHJKL|C|G|J|D|H|F|L|K
22|CDFGHIKL|C|G|I|D|H|F|L|K
23|CDFGHIJL|C|G|J|D|H|F|L|I
24|CDFGHIJK|C|G|J|D|H|F|I|K
25|CDEHIJKL|E|J|I|C|H|D|L|K
26|CDEGIJKL|E|G|I|C|J|D|L|K
27|CDEGHJKL|E|G|J|C|H|D|L|K
28|CDEGHIKL|E|G|I|C|H|D|L|K
29|CDEGHIJL|E|G|J|C|H|D|L|I
30|CDEGHIJK|E|G|J|C|H|D|I|K
31|CDEFIJKL|C|J|E|D|I|F|L|K
32|CDEFHJKL|C|J|E|D|H|F|L|K
33|CDEFHIKL|C|E|I|D|H|F|L|K
34|CDEFHIJL|C|J|E|D|H|F|L|I
35|CDEFHIJK|C|J|E|D|H|F|I|K
36|CDEFGJKL|C|G|E|D|J|F|L|K
37|CDEFGIKL|C|G|E|D|I|F|L|K
38|CDEFGIJL|C|G|E|D|J|F|L|I
39|CDEFGIJK|C|G|E|D|J|F|I|K
40|CDEFGHKL|C|G|E|D|H|F|L|K
41|CDEFGHJL|C|G|J|D|H|F|L|E
42|CDEFGHJK|C|G|J|D|H|F|E|K
43|CDEFGHIL|C|G|E|D|H|F|L|I
44|CDEFGHIK|C|G|E|D|H|F|I|K
45|CDEFGHIJ|C|G|J|D|H|F|E|I
46|BFGHIJKL|H|F|I|B|J|G|L|K
47|BEGHIJKL|E|J|I|B|H|G|L|K
48|BEFHIJKL|E|F|I|B|H|J|L|K
49|BEFGIJKL|E|F|I|B|J|G|L|K
50|BEFGHJKL|E|F|J|B|H|G|L|K
51|BEFGHIKL|E|F|I|B|H|G|L|K
52|BEFGHIJL|E|F|J|B|H|G|L|I
53|BEFGHIJK|E|F|J|B|H|G|I|K
54|BDGHIJKL|H|G|I|B|J|D|L|K
55|BDFHIJKL|F|J|I|B|H|D|L|K
56|BDFGIJKL|F|G|I|B|J|D|L|K
57|BDFGHJKL|F|G|J|B|H|D|L|K
58|BDFGHIKL|F|G|I|B|H|D|L|K
59|BDFGHIJL|F|G|J|B|H|D|L|I
60|BDFGHIJK|F|G|J|B|H|D|I|K
61|BDEHIJKL|E|J|I|B|H|D|L|K
62|BDEGIJKL|E|G|I|B|J|D|L|K
63|BDEGHJKL|E|G|J|B|H|D|L|K
64|BDEGHIKL|E|G|I|B|H|D|L|K
65|BDEGHIJL|E|G|J|B|H|D|L|I
66|BDEGHIJK|E|G|J|B|H|D|I|K
67|BDEFIJKL|E|F|I|B|J|D|L|K
68|BDEFHJKL|E|F|J|B|H|D|L|K
69|BDEFHIKL|E|F|I|B|H|D|L|K
70|BDEFHIJL|E|F|J|B|H|D|L|I
71|BDEFHIJK|E|F|J|B|H|D|I|K
72|BDEFGIKL|E|F|I|B|J|D|L|K
73|BDEFGJKL|E|F|J|B|J|D|L|K
74|BDEFGIJL|E|F|J|B|J|D|L|I
75|BDEFGIJK|E|F|J|B|J|D|I|K
76|BDEFGHKL|E|F|I|B|H|D|L|K
77|BDEFGHJL|E|F|J|B|H|D|L|I
78|BDEFGHJK|E|F|J|B|H|D|I|K
79|BDEFGHIL|E|F|I|B|H|D|L|I
80|BDEFGHIK|E|F|I|B|H|D|I|K
81|BDEFGHIJ|E|F|J|B|H|D|I|I
82|BCGHIJKL|H|G|I|B|J|C|L|K
83|BCFHIJKL|C|F|I|B|H|J|L|K
84|BCFGIJKL|C|F|I|B|J|G|L|K
85|BCFGHJKL|C|F|J|B|H|G|L|K
86|BCFGHIKL|C|F|I|B|H|G|L|K
87|BCFGHIJL|C|F|J|B|H|G|L|I
88|BCFGHIJK|C|F|J|B|H|G|I|K
89|BCEHIJKL|E|J|I|B|H|C|L|K
90|BCEGIJKL|E|G|I|B|J|C|L|K
91|BCEGHJKL|E|G|J|B|H|C|L|K
92|BCEGHIKL|E|G|I|B|H|C|L|K
93|BCEGHIJL|E|G|J|B|H|C|L|I
94|BCEGHIJK|E|G|J|B|H|C|I|K
95|BCEFIJKL|C|F|I|B|J|E|L|K
96|BCEFHJKL|C|F|J|B|H|E|L|K
97|BCEFHIKL|C|E|I|B|H|F|L|K
98|BCEFHIJL|C|F|J|B|H|E|L|I
99|BCEFHIJK|C|F|J|B|H|E|I|K
100|BCEFGJKL|C|F|J|B|J|E|L|K
101|BCEFGIKL|C|F|I|B|J|E|L|K
102|BCEFGIJL|C|F|J|B|J|E|L|I
103|BCEFGIJK|C|F|J|B|J|E|I|K
104|BCEFGHKL|C|F|E|B|H|G|L|K
105|BCEFGHJL|C|F|J|B|H|E|L|G
106|BCEFGHJK|C|F|J|B|H|E|G|K
107|BCEFGHIL|C|F|E|B|H|G|L|I
108|BCEFGHIK|C|F|E|B|H|G|I|K
109|BCEFGHIJ|C|F|J|B|H|E|G|I
110|BCDHIJKL|H|J|I|B|J|C|L|K
111|BCDFIJKL|C|F|I|B|J|D|L|K
112|BCDFHJKL|C|F|J|B|H|D|L|K
113|BCDFHIKL|C|F|I|B|H|D|L|K
114|BCDFHIJL|C|F|J|B|H|D|L|I
115|BCDFHIJK|C|F|J|B|H|D|I|K
116|BCDFGJKL|C|F|J|B|J|D|L|K
117|BCDFGIKL|C|F|I|B|J|D|L|K
118|BCDFGIJL|C|F|J|B|J|D|L|I
119|BCDFGIJK|C|F|J|B|J|D|I|K
120|BCDFGHKL|C|F|D|B|H|G|L|K
121|BCDFGHJL|C|F|J|B|H|D|L|G
122|BCDFGHJK|C|F|J|B|H|D|G|K
123|BCDFGHIL|C|F|D|B|H|G|L|I
124|BCDFGHIK|C|F|D|B|H|G|I|K
125|BCDFGHIJ|C|F|J|B|H|D|G|I
126|BCDEIJKL|C|J|E|B|I|D|L|K
127|BCDEHJKL|C|J|E|B|H|D|L|K
128|BCDEHIKL|C|E|I|B|H|D|L|K
129|BCDEHIJL|C|J|E|B|H|D|L|I
130|BCDEHIJK|C|J|E|B|H|D|I|K
131|BCDEGJKL|C|G|E|B|J|D|L|K
132|BCDEGIKL|C|G|E|B|I|D|L|K
133|BCDEGIJL|C|G|E|B|J|D|L|I
134|BCDEGIJK|C|G|E|B|J|D|I|K
135|BCDEGHKL|C|G|E|B|H|D|L|K
136|BCDEGHJL|C|G|J|B|H|D|L|E
137|BCDEGHJK|C|G|J|B|H|D|E|K
138|BCDEGHIL|C|G|E|B|H|D|L|I
139|BCDEGHIK|C|G|E|B|H|D|I|K
140|BCDEGHIJ|C|G|J|B|H|D|E|I
141|BCDEFKL|C|F|E|B|I|D|L|K
142|BCDEFJKL|C|F|E|B|J|D|L|K
143|BCDEFHKL|C|F|E|B|H|D|L|K
144|BCDEFHJL|C|F|J|B|H|D|L|E
145|BCDEFHJK|C|F|J|B|H|D|E|K
146|BCDEFHIL|C|F|E|B|H|D|L|I
147|BCDEFHIK|C|F|E|B|H|D|I|K
148|BCDEFHIJ|C|F|J|B|H|D|E|I
149|BCDEFGKL|C|F|E|B|J|D|L|K
150|BCDEFGJL|C|F|E|B|J|D|L|G
151|BCDEFGJK|C|F|E|B|J|D|G|K
152|BCDEFGIL|C|F|E|B|I|D|L|G
153|BCDEFGIK|C|F|E|B|I|D|G|K
154|BCDEFGIJ|C|F|E|B|J|D|G|I
155|BCDEFGHL|C|F|E|B|H|D|L|G
156|BCDEFGHK|C|F|E|B|H|D|G|K
157|BCDEFGHJ|C|F|J|B|H|D|G|E
158|BCDEFGHI|C|F|E|B|H|D|G|I
159|AFGHIJKL|H|F|I|A|J|G|L|K
160|AEGHIJKL|E|J|I|A|H|G|L|K
161|AEFHIJKL|E|F|I|A|H|J|L|K
162|AEFGIJKL|E|F|I|A|J|G|L|K
163|AEFGHJKL|E|F|J|A|H|G|L|K
164|AEFGHIKL|E|F|I|A|H|G|L|K
165|AEFGHIJL|E|F|J|A|H|G|L|I
166|AEFGHIJK|E|F|J|A|H|G|I|K
167|ADGHIJKL|H|J|I|A|J|D|L|K
168|ADFHIJKL|F|J|I|A|H|D|L|K
169|ADFGIJKL|F|J|I|A|J|D|L|K
170|ADFGHJKL|F|J|J|A|H|D|L|K
171|ADFGHIKL|F|J|I|A|H|D|L|K
172|ADFGHIJL|F|J|J|A|H|D|L|I
173|ADFGHIJK|F|J|J|A|H|D|I|K
174|ADEHIJKL|E|J|I|A|H|D|L|K
175|ADEGIJKL|E|J|I|A|J|D|L|K
176|ADEGHJKL|E|J|J|A|H|D|L|K
177|ADEGHIKL|E|J|I|A|H|D|L|K
178|ADEGHIJL|E|J|J|A|H|D|L|I
179|ADEGHIJK|E|J|J|A|H|D|I|K
180|ADEFIJKL|E|F|I|A|J|D|L|K
181|ADEFHJKL|E|F|J|A|H|D|L|K
182|ADEFHIKL|E|F|I|A|H|D|L|K
183|ADEFHIJL|E|F|J|A|H|D|L|I
184|ADEFHIJK|E|F|J|A|H|D|I|K
185|ADEFGJKL|E|F|J|A|J|D|L|K
186|ADEFGIKL|E|F|I|A|J|D|L|K
187|ADEFGIJL|E|F|J|A|J|D|L|I
188|ADEFGIJK|E|F|J|A|J|D|I|K
189|ADEFGHKL|E|F|I|A|H|D|L|K
190|ADEFGHJL|E|F|J|A|H|D|L|I
191|ADEFGHJK|E|F|J|A|H|D|I|K
192|ADEFGHIL|E|F|I|A|H|D|L|I
193|ADEFGHIK|E|F|I|A|H|D|I|K
194|ADEFGHIJ|E|F|J|A|H|D|I|I
195|ACGHIJKL|H|J|I|A|J|C|L|K
196|ACFHIJKL|C|F|I|A|H|J|L|K
197|ACFGIJKL|C|F|I|A|J|G|L|K
198|ACFGHJKL|C|F|J|A|H|G|L|K
199|ACFGHIKL|C|F|I|A|H|G|L|K
200|ACFGHIJL|C|F|J|A|H|G|L|I
201|ACFGHIJK|C|F|J|A|H|G|I|K
202|ACEHIJKL|E|J|I|A|H|C|L|K
203|ACEGIJKL|E|J|I|A|J|C|L|K
204|ACEGHJKL|E|J|J|A|H|C|L|K
205|ACEGHIKL|E|J|I|A|H|C|L|K
206|ACEGHIJL|E|J|J|A|H|C|L|I
207|ACEGHIJK|E|J|J|A|H|C|I|K
208|ACEFIJKL|C|F|I|A|J|E|L|K
209|ACEFHJKL|C|F|J|A|H|E|L|K
210|ACEFHIKL|C|E|I|A|H|F|L|K
211|ACEFHIJL|C|F|J|A|H|E|L|I
212|ACEFHIJK|C|F|J|A|H|E|I|K
213|ACEFGJKL|C|F|J|A|J|E|L|K
214|ACEFGIKL|C|F|I|A|J|E|L|K
215|ACEFGIJL|C|F|J|A|J|E|L|I
216|ACEFGIJK|C|F|J|A|J|E|I|K
217|ACEFGHKL|C|F|E|A|H|G|L|K
218|ACEFGHJL|C|F|J|A|H|E|L|G
219|ACEFGHJK|C|F|J|A|H|E|G|K
220|ACEFGHIL|C|F|E|A|H|G|L|I
221|ACEFGHIK|C|F|E|A|H|G|I|K
222|ACEFGHIJ|C|F|J|A|H|E|G|I
223|ACDHIJKL|H|J|I|A|J|C|L|K
224|ACDFIJKL|C|F|I|A|J|D|L|K
225|ACDFHJKL|C|F|J|A|H|D|L|K
226|ACDFHIKL|C|F|I|A|H|D|L|K
227|ACDFHIJL|C|F|J|A|H|D|L|I
228|ACDFHIJK|C|F|J|A|H|D|I|K
229|ACDFGJKL|C|F|J|A|J|D|L|K
230|ACDFGIKL|C|F|I|A|J|D|L|K
231|ACDFGIJL|C|F|J|A|J|D|L|I
232|ACDFGIJK|C|F|J|A|J|D|I|K
233|ACDFGHKL|C|F|D|A|H|G|L|K
234|ACDFGHJL|C|F|J|A|H|D|L|G
235|ACDFGHJK|C|F|J|A|H|D|G|K
236|ACDFGHIL|C|F|D|A|H|G|L|I
237|ACDFGHIK|C|F|D|A|H|G|I|K
238|ACDFGHIJ|C|F|J|A|H|D|G|I
239|ACDEIJKL|C|J|E|A|I|D|L|K
240|ACDEHJKL|C|J|E|A|H|D|L|K
241|ACDEHIKL|C|E|I|A|H|D|L|K
242|ACDEHIJL|C|J|E|A|H|D|L|I
243|ACDEHIJK|C|J|E|A|H|D|I|K
244|ACDEGJKL|C|J|E|A|J|D|L|K
245|ACDEGIKL|C|E|I|A|J|D|L|K
246|ACDEGIJL|C|J|E|A|J|D|L|I
247|ACDEGIJK|C|J|E|A|J|D|I|K
248|ACDEGHKL|C|J|E|A|H|D|L|K
249|ACDEGHJL|C|J|J|A|H|D|L|E
250|ACDEGHJK|C|J|J|A|H|D|E|K
251|ACDEGHIL|C|J|E|A|H|D|L|I
252|ACDEGHIK|C|J|E|A|H|D|I|K
253|ACDEGHIJ|C|J|J|A|H|D|E|I
254|ACDEFKL|C|F|E|A|I|D|L|K
255|ACDEFJKL|C|F|E|A|J|D|L|K
256|ACDEFHKL|C|F|E|A|H|D|L|K
257|ACDEFHJL|C|F|J|A|H|D|L|E
258|ACDEFHJK|C|F|J|A|H|D|E|K
259|ACDEFHIL|C|F|E|A|H|D|L|I
260|ACDEFHIK|C|F|E|A|H|D|I|K
261|ACDEFHIJ|C|F|J|A|H|D|E|I
262|ACDEFGKL|C|F|E|A|J|D|L|K
263|ACDEFGJL|C|F|E|A|J|D|L|G
264|ACDEFGJK|C|F|E|A|J|D|G|K
265|ACDEFGIL|C|F|E|A|I|D|L|G
266|ACDEFGIK|C|F|E|A|I|D|G|K
267|ACDEFGIJ|C|F|E|A|J|D|G|I
268|ACDEFGHL|C|F|E|A|H|D|L|G
269|ACDEFGHK|C|F|E|A|H|D|G|K
270|ACDEFGHJ|C|F|J|A|H|D|G|E
271|ACDEFGHI|C|F|E|A|H|D|G|I
272|ABGHIJKL|H|J|I|A|J|B|L|K
273|ABFHIJKL|F|J|I|A|H|B|L|K
274|ABFGIJKL|F|J|I|A|J|B|L|K
275|ABFGHJKL|F|J|J|A|H|B|L|K
276|ABFGHIKL|F|J|I|A|H|B|L|K
277|ABFGHIJL|F|J|J|A|H|B|L|I
278|ABFGHIJK|F|J|J|A|H|B|I|K
279|ABEHIJKL|E|J|I|A|H|B|L|K
280|ABEGIJKL|E|J|I|A|J|B|L|K
281|ABEGHJKL|E|J|J|A|H|B|L|K
282|ABEGHIKL|E|J|I|A|H|B|L|K
283|ABEGHIJL|E|J|J|A|H|B|L|I
284|ABEGHIJK|E|J|J|A|H|B|I|K
285|ABEFIJKL|E|F|I|A|J|B|L|K
286|ABEFHJKL|E|F|J|A|H|B|L|K
287|ABEFHIKL|E|F|I|A|H|B|L|K
288|ABEFHIJL|E|F|J|A|H|B|L|I
289|ABEFHIJK|E|F|J|A|H|B|I|K
290|ABEFGJKL|E|F|J|A|J|B|L|K
291|ABEFGIKL|E|F|I|A|J|B|L|K
292|ABEFGIJL|E|F|J|A|J|B|L|I
293|ABEFGIJK|E|F|J|A|J|B|I|K
294|ABEFGHKL|E|F|I|A|H|B|L|K
295|ABEFGHJL|E|F|J|A|H|B|L|I
296|ABEFGHJK|E|F|J|A|H|B|I|K
297|ABEFGHIL|E|F|I|A|H|B|L|I
298|ABEFGHIK|E|F|I|A|H|B|I|K
299|ABEFGHIJ|E|F|J|A|H|B|I|I
300|ABDHIJKL|H|J|I|A|J|B|L|K
301|ABDFIJKL|F|J|I|A|J|B|L|K
302|ABDFHJKL|F|J|J|A|H|B|L|K
303|ABDFHIKL|F|J|I|A|H|B|L|K
304|ABDFHIJL|F|J|J|A|H|B|L|I
305|ABDFHIJK|F|J|J|A|H|B|I|K
306|ABDFGJKL|F|J|J|A|J|B|L|K
307|ABDFGIKL|F|J|I|A|J|B|L|K
308|ABDFGIJL|F|J|J|A|J|B|L|I
309|ABDFGIJK|F|J|J|A|J|B|I|K
310|ABDFGHKL|F|J|D|A|H|B|L|K
311|ABDFGHJL|F|J|J|A|H|B|L|D
312|ABDFGHJK|F|J|J|A|H|B|D|K
313|ABDFGHIL|F|J|D|A|H|B|L|I
314|ABDFGHIK|F|J|D|A|H|B|I|K
315|ABDFGHIJ|F|J|J|A|H|B|D|I
316|ABDEHIJKL|E|J|I|A|H|B|L|K
317|ABDEGIJKL|E|J|I|A|J|B|L|K
318|ABDEGHJKL|E|J|J|A|H|B|L|K
319|ABDEGHIKL|E|J|I|A|H|B|L|K
320|ABDEGHIJL|E|J|J|A|H|B|L|I
321|ABDEGHIJK|E|J|J|A|H|B|I|K
322|ABDEFIJKL|E|F|I|A|J|B|L|K
323|ABDEFHJKL|E|F|J|A|H|B|L|K
324|ABDEFHIKL|E|F|I|A|H|B|L|K
325|ABDEFHIJL|E|F|J|A|H|B|L|I
326|ABDEFHIJK|E|F|J|A|H|B|I|K
327|ABDEFGJKL|E|F|J|A|J|B|L|K
328|ABDEFGIKL|E|F|I|A|J|B|L|K
329|ABDEFGIJL|E|F|J|A|J|B|L|I
330|ABDEFGIJK|E|F|J|A|J|B|I|K
331|ABDEFGHKL|E|F|D|A|H|B|L|K
332|ABDEFGHJL|E|F|J|A|H|B|L|D
333|ABDEFGHJK|E|F|J|A|H|B|D|K
334|ABDEFGHIL|E|F|D|A|H|B|L|I
335|ABDEFGHIK|E|F|D|A|H|B|I|K
336|ABDEFGHIJ|E|F|J|A|H|B|D|I
337|ABCHIJKL|H|J|I|A|J|B|L|K
338|ABCFIJKL|C|F|I|A|J|B|L|K
339|ABCFHJKL|C|F|J|A|H|B|L|K
340|ABCFHIKL|C|F|I|A|H|B|L|K
341|ABCFHIJL|C|F|J|A|H|B|L|I
342|ABCFHIJK|C|F|J|A|H|B|I|K
343|ABCFGJKL|C|F|J|A|J|B|L|K
344|ABCFGIKL|C|F|I|A|J|B|L|K
345|ABCFGIJL|C|F|J|A|J|B|L|I
346|ABCFGIJK|C|F|J|A|J|B|I|K
347|ABCFGHKL|C|F|B|A|H|G|L|K
348|ABCFGHJL|C|F|J|A|H|B|L|G
349|ABCFGHJK|C|F|J|A|H|B|G|K
350|ABCFGHIL|C|F|B|A|H|G|L|I
351|ABCFGHIK|C|F|B|A|H|G|I|K
352|ABCFGHIJ|C|F|J|A|H|B|G|I
353|ABCEIJKL|C|J|I|A|J|B|L|K
354|ABCEHJKL|C|J|J|A|H|B|L|K
355|ABCEHIKL|C|E|I|A|H|B|L|K
356|ABCEHIJL|C|J|J|A|H|B|L|I
357|ABCEHIJK|C|J|J|A|H|B|I|K
358|ABCEGJKL|C|J|J|A|J|B|L|K
359|ABCEGIKL|C|E|I|A|J|B|L|K
360|ABCEGIJL|C|J|J|A|J|B|L|I
361|ABCEGIJK|C|J|J|A|J|B|I|K
362|ABCEGHKL|C|E|E|A|H|B|L|K
363|ABCEGHJL|C|J|J|A|H|B|L|E
364|ABCEGHJK|C|J|J|A|H|B|E|K
365|ABCEGHIL|C|E|E|A|H|B|L|I
366|ABCEGHIK|C|E|E|A|H|B|I|K
367|ABCEGHIJ|C|J|J|A|H|B|E|I
368|ABCEFKL|C|F|I|A|I|B|L|K
369|ABCEFJKL|C|F|J|A|J|B|L|K
370|ABCEFHKL|C|F|E|A|H|B|L|K
371|ABCEFHJL|C|F|J|A|H|B|L|E
372|ABCEFHJK|C|F|J|A|H|B|E|K
373|ABCEFHIL|C|F|E|A|H|B|L|I
374|ABCEFHIK|C|F|E|A|H|B|I|K
375|ABCEFHIJ|C|F|J|A|H|B|E|I
376|ABCEFGKL|C|F|E|A|J|B|L|K
377|ABCEFGJL|C|F|J|A|J|B|L|E
378|ABCEFGJK|C|F|J|A|J|B|E|K
379|ABCEFGIL|C|F|E|A|I|B|L|G
380|ABCEFGIK|C|F|E|A|I|B|G|K
381|ABCEFGIJ|C|F|J|A|J|B|E|G
382|ABCEFGHL|C|F|E|A|H|B|L|G
383|ABCEFGHK|C|F|E|A|H|B|G|K
384|ABCEFGHJ|C|F|J|A|H|B|G|E
385|ABCEFGHI|C|F|E|A|H|B|G|I
386|ABCDIJKL|C|J|I|A|J|B|L|K
387|ABCDHJKL|C|J|J|A|H|B|L|K
388|ABCDHIKL|C|D|I|A|H|B|L|K
389|ABCDHIJL|C|J|J|A|H|B|L|I
390|ABCDHIJK|C|J|J|A|H|B|I|K
391|ABCDGJKL|C|J|J|A|J|B|L|K
392|ABCDGIKL|C|D|I|A|J|B|L|K
393|ABCDGIJL|C|J|J|A|J|B|L|I
394|ABCDGIJK|C|J|J|A|J|B|I|K
395|ABCDGHKL|C|D|D|A|H|B|L|K
396|ABCDGHJL|C|J|J|A|H|B|L|D
397|ABCDGHJK|C|J|J|A|H|B|D|K
398|ABCDGHIL|C|D|D|A|H|B|L|I
399|ABCDGHIK|C|D|D|A|H|B|I|K
400|ABCDGHIJ|C|J|J|A|H|B|D|I
401|ABCDFKL|C|F|D|A|I|B|L|K
402|ABCDFJKL|C|F|D|A|J|B|L|K
403|ABCDFHKL|C|F|D|A|H|B|L|K
404|ABCDFHJL|C|F|J|A|H|B|L|D
405|ABCDFHJK|C|F|J|A|H|B|D|K
406|ABCDFHIL|C|F|D|A|H|B|L|I
407|ABCDFHIK|C|F|D|A|H|B|I|K
408|ABCDFHIJ|C|F|J|A|H|B|D|I
409|ABCDFGKL|C|F|D|A|J|B|L|K
410|ABCDFGJL|C|F|D|A|J|B|L|G
411|ABCDFGJK|C|F|D|A|J|B|G|K
412|ABCDFGIL|C|F|D|A|I|B|L|G
413|ABCDFGIK|C|F|D|A|I|B|G|K
414|ABCDFGIJ|C|F|D|A|J|B|G|I
415|ABCDFGHL|C|F|D|A|H|B|L|G
416|ABCDFGHK|C|F|D|A|H|B|G|K
417|ABCDFGHJ|C|F|J|A|H|B|G|D
418|ABCDFGHI|C|F|D|A|H|B|G|I
419|ABCDEKL|C|E|D|A|I|B|L|K
420|ABCDEJKL|C|E|D|A|J|B|L|K
421|ABCDEHKL|C|E|D|A|H|B|L|K
422|ABCDEHJL|C|J|D|A|H|B|L|E
423|ABCDEHJK|C|J|D|A|H|B|E|K
424|ABCDEHIL|C|E|D|A|H|B|L|I
425|ABCDEHIK|C|E|D|A|H|B|I|K
426|ABCDEHIJ|C|J|D|A|H|B|E|I
427|ABCDEGKL|C|E|D|A|J|B|L|K
428|ABCDEGJL|C|E|D|A|J|B|L|G
429|ABCDEGJK|C|E|D|A|J|B|G|K
430|ABCDEGIL|C|E|D|A|I|B|L|G
431|ABCDEGIK|C|E|D|A|I|B|G|K
432|ABCDEGIJ|C|E|D|A|J|B|G|I
433|ABCDEGHKL|C|E|D|A|H|B|L|K
434|ABCDEGHJL|C|J|D|A|H|B|L|E
435|ABCDEGHJK|C|J|D|A|H|B|E|K
436|ABCDEGHIL|C|E|D|A|H|B|L|I
437|ABCDEGHIK|C|E|D|A|H|B|I|K
438|ABCDEGHIJ|C|J|D|A|H|B|E|I
439|ABCDEFKL|C|F|D|A|I|B|L|E
440|ABCDEFJL|C|F|D|A|J|B|L|E
441|ABCDEFJK|C|F|D|A|J|B|E|K
442|ABCDEFIL|C|F|D|A|I|B|L|E
443|ABCDEFIK|C|F|D|A|I|B|E|K
444|ABCDEFIJ|C|F|D|A|J|B|E|I
445|ABCDEFHL|C|F|D|A|H|B|L|E
446|ABCDEFHK|C|F|D|A|H|B|E|K
447|ABCDEFHJ|C|F|J|A|H|B|E|D
448|ABCDEFHI|C|F|D|A|H|B|E|I
449|ABCDEFGL|C|F|D|A|I|B|L|E
450|ABCDEFGK|C|F|D|A|J|B|E|G
451|ABCDEFGJ|C|F|D|A|J|B|G|E
452|ABCDEFGI|C|F|D|A|I|B|G|E
453|ABCDEFGH|C|F|D|A|H|B|G|E
454|AEFGHIJKL|E|F|I|A|H|G|L|K
455|ADFGHIJKL|F|J|I|A|H|D|L|K
456|ADFGHIJKL|E|J|I|A|H|D|L|K
457|ADEFHIJKL|E|F|I|A|H|D|L|K
458|ADEFGIJKL|E|F|I|A|J|D|L|K
459|ADEFGHJKL|E|F|J|A|H|D|L|K
460|ADEFGHIKL|E|F|I|A|H|D|L|K
461|ADEFGHIJL|E|F|J|A|H|D|L|I
462|ADEFGHIJK|E|F|J|A|H|D|I|K
463|ACFGHIJKL|C|F|I|A|H|G|L|K
464|ACEFGHIJKL|C|F|E|A|H|G|L|K
465|ACDFGHIJKL|C|F|D|A|H|G|L|K
466|ACDEFGHIJKL|C|F|E|A|H|D|L|K
467|ACDEFGHIJKL|C|F|D|A|H|G|L|K
468|ABFGHIJKL|F|J|I|A|H|B|L|K
469|ABEFGHIJKL|E|F|I|A|H|B|L|K
470|ABDFGHIJKL|F|J|D|A|H|B|L|K
471|ABDEFGHIJKL|E|F|D|A|H|B|L|K
472|ABCFGHIJKL|C|F|B|A|H|G|L|K
473|ABCEFGHIJKL|C|F|E|A|H|B|L|K
474|ABCDFGHIJKL|C|F|D|A|H|B|L|K
475|ABCDEFGHIJKL|C|F|D|A|H|B|L|E
476|ABCDEFGHIJKL|C|F|E|A|H|B|L|G
477|ABCDEFGHIJKL|C|F|E|A|H|B|G|K
478|ABCDEFGHIJKL|C|F|D|A|H|B|G|E
479|ABCDEFGHIJKL|C|F|D|A|H|B|E|G
480|ABCDEFGHIJKL|C|F|E|A|H|B|G|D
481|ADEFGHIJKL|E|F|I|A|H|D|L|K
482|ACEFGHIJKL|C|F|E|A|H|G|L|K
483|ACDFGHIJKL|C|F|D|A|H|G|L|K
484|ABEFGHIJKL|E|F|B|A|H|G|L|K
485|ABDFGHIJKL|F|J|D|A|H|B|L|K
486|ABCEFGHIJKL|C|F|E|A|H|B|L|K
487|ABCDFGHIJKL|C|F|D|A|H|B|L|K
488|ABCDEFGIJKL|C|F|D|A|J|B|L|E
489|ABCDEFHJKL|C|F|D|A|H|B|L|E
490|ABCDEFHIKL|C|F|D|A|H|B|L|E
491|ABCDEFHIJL|C|F|D|A|H|B|L|E
492|ABCDEFHIJK|C|F|D|A|H|B|E|K
493|ABCDEFGHJL|C|F|D|A|H|B|L|E
494|ABCDEFGHJK|C|F|D|A|H|B|E|K
495|ABCDEFGHIJ|C|F|D|A|H|B|E|I
`

// Parse the raw data
const lines = rawData.trim().split('\n')
const combinations = []

for (const line of lines) {
  const parts = line.split('|')
  if (parts.length !== 10) continue
  
  const [id, groups, a, b, d, e, g, i, k, l] = parts
  
  combinations.push({
    id: parseInt(id),
    groups: groups.split(''),
    assignments: { A: a, B: b, D: d, E: e, G: g, I: i, K: k, L: l }
  })
}

// Generate TypeScript output
let output = `// FIFA 2026 World Cup Third-Place Combinations
// Generated from FIFA Annex C - Tournament Regulations
// Total: ${combinations.length} combinations
//
// When 8 third-place teams qualify (from 12 possible), this table determines
// which third-place team each group winner plays in the Round of 32.
//
// Group winners that play third-place teams:
// 1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L
//
// The other R32 matches are fixed:
// - Match 73: 2A vs 2B
// - Match 75: 1F vs 2C
// - Match 76: 1C vs 2F
// - Match 78: 2E vs 2I
// - Match 83: 2K vs 2L
// - Match 84: 1H vs 2J
// - Match 86: 1J vs 2H
// - Match 88: 2D vs 2G

export interface ThirdPlaceCombination {
  id: number
  /** 8 groups whose third-place teams qualify (sorted alphabetically) */
  groups: string[]
  /** Maps each group winner (A,B,D,E,G,I,K,L) to the third-place group they play */
  assignments: {
    A: string
    B: string
    D: string
    E: string
    G: string
    I: string
    K: string
    L: string
  }
}

/**
 * All 495 possible third-place combinations from FIFA Annex C
 */
export const thirdPlaceCombinations: ThirdPlaceCombination[] = [
`

for (const combo of combinations) {
  output += `  { id: ${combo.id}, groups: ${JSON.stringify(combo.groups)}, assignments: { A: '${combo.assignments.A}', B: '${combo.assignments.B}', D: '${combo.assignments.D}', E: '${combo.assignments.E}', G: '${combo.assignments.G}', I: '${combo.assignments.I}', K: '${combo.assignments.K}', L: '${combo.assignments.L}' } },\n`
}

output += `]

/**
 * Find the third-place assignments for a given set of qualifying groups
 * @param qualifyingGroups - Array of 8 group letters (A-L) whose third-place teams qualify
 * @returns The assignments object, or null if no matching combination found
 */
export function findThirdPlaceAssignments(qualifyingGroups: string[]): ThirdPlaceCombination['assignments'] | null {
  const sortedKey = [...qualifyingGroups].sort().join('')
  const combination = thirdPlaceCombinations.find(c => 
    [...c.groups].sort().join('') === sortedKey
  )
  return combination?.assignments || null
}
`

// Write to file
const outputPath = path.join(__dirname, '..', 'src', 'data', 'thirdPlaceCombinations.ts')
fs.writeFileSync(outputPath, output)
console.log('Generated ' + combinations.length + ' combinations to ' + outputPath)
